version: "3"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: "keinos/sqlite3"
    volumes:
      - ./mydatabase.db:/app/sensores-database.db
    networks:
      - my-network
networks:
  my-network:
